name: go build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: go/go.sum

      - name: Install dependencies
        working-directory: go
        run: go mod tidy
      - name: Install dependencies (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y libwebp-dev mingw-w64
      - name: Build binaries
        working-directory: go
        run: |
          mkdir -p ../build
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ../build/app-linux-amd64 ./cmd
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o ../build/app-windows-amd64.exe ./cmd
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o ../build/app-macos-amd64 ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: build/*