name: go build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: go/go.sum

      - name: Install dependencies
        working-directory: go
        run: go mod tidy
      - name: Build binaries
        working-directory: go
        run: |
          mkdir -p ../build
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ../build/app-linux-amd64 ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: build/*
          compression-level: 0  # 禁用压缩
  build_freebsd:
    runs-on: freebsd-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: go/go.sum

      - name: Install dependencies
        working-directory: go
        run: go mod tidy
      - name: Build binaries
        working-directory: go
        run: |
          mkdir -p ../build
          CGO_ENABLED=1 GOOS=freebsd GOARCH=amd64 go build -o ../build/app-freebsd-amd64 ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: build/*
          compression-level: 0  # 禁用压缩
