name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, 386, armv7, arm64, aarch64, freebsd-amd64]
        goos: [linux, freebsd]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      - name: Build binaries
        run: |
          mkdir -p build
          CGO_ENABLED=1 GOARCH=${{ matrix.goarch }} GOOS=${{ matrix.goos }} go build -o build/app-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: build/*
